apiVersion: apps/v1
kind: Deployment
metadata:
  name: labmap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      transpire.ocf.io/deployment: labmap-frontend
  template:
    metadata:
      labels:
        transpire.ocf.io/deployment: labmap-frontend
    spec:
      containers:
      - image: ghcr.io/ocf/labmap2-frontend:8673a08901e3b8f26d74cc0856a67e5635e548f9
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 8080
      dnsConfig:
        searches:
        - ocf.berkeley.edu
      dnsPolicy: ClusterFirst
