apiVersion: apps/v1
kind: Deployment
metadata:
  name: labmap-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      transpire.ocf.io/deployment: labmap-frontend
  template:
    metadata:
      labels:
        transpire.ocf.io/deployment: labmap-frontend
    spec:
      containers:
      - image: ghcr.io/ocf/labmap2-frontend:ae3ac03c5fad87fa9d16d9df2d24698db11e5176
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 8080
      dnsConfig:
        searches:
        - ocf.berkeley.edu
      dnsPolicy: ClusterFirst
