apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-mutating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9KSndqTldUbVFUcUtHRGJHSTMxdll3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TlRFeU1UUXdOak00TURoYUZ3MHpNREV5TVRNdwpOak00TURoYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFFUamVBN3RQU1htL0g2UUplNDV3U3cKN3BVVGNpRWVYRmlMMUU2NnpiK3B1ZUlwT1dIaTRJZEhWQVljbHlwV1pOQm5uV3M0bVUyOVFTNngxa0JpZEp2SApRZlZVOGV5WHZoWHNpQXdmc28zejdRdDAwT1NzM3B0R0M2eVI0ZkVvSDNyVmRqaVlzc2tHdmdXNC9PcFlkU2x2CkZTdEFSSWJZbXVvL0FRTGxsaFowYXJwV3Y1OVZmVStPWVNhVFNKSnlJQUhJc3dIbWRXeExXSTBoVDRKT1ZVeWEKeFJTRG1hUW5qMEJrZGl0dWlEZ2NmS3NhbFRpQzE2M1pBMzZ2VDRjc1lkYTBSK0N6dHdaREFqbVpDdndIVmtFdApZWFR1UkE5NDhRTFI3cDE2MmJ4Tk4xRkEvQm9QaUttZm15L3BVeEtzMXF5K25oRTh2MUZmWVhLOFN2ODQrRThDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVOVRTeFI3emRzOUxTVHhyWgp1d0ViTVE2RWxwTXdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFaakRBbXhGQ29XQmpHM1hEM1ZXTWk2WjA3MUxGbkIrcUNuZm0zb284U3ZzYgpISkVNRlJ2YWF3dzJ2NlZZR3c2UVlyTEpvcU5US2NmQjRSNG9JbFlPalh2NU5TZHVQcGNzcDhlbm4rUnJsSmhxClZaWHJXUGkvcW50REx5amxRNzk0RklqY2ppVTBSN0xWNU45YklsZnFoaGkzalhhRVdVQ3ZtajFXUlgxSjMxa0UKRjk3QVFFdGdUZ3h5aEVTU1dkWEJ5QnNrZzE5Tm9WemZBSDhrZTcwS2ttVWRHWVdHZHFON2ViUTVCU0t4Y1dzcgpyeWtaeUF6VXEzdFY1UmZjdkFYNURyTERnaWZaWDBRRExTTzkwUGpUaWNWQ1VscVQza1krb0J1Wkdkcmw5K1B6CkVOMlA0THkxWmdqY09tcW1oSGU2eGU0bFk1NHI4UzduWFBLcUd3U2t5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /mutate-fission-io-v1-package
  failurePolicy: Fail
  name: mpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
